# Generated by Django 2.1.5 on 2020-02-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_user_data_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
