# Generated by Django 2.1.5 on 2020-02-18 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_monument_reviews_searched_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument_reviews',
            name='date',
            field=models.DateField(default=datetime.date(2020, 2, 18)),
        ),
    ]
