# Generated by Django 2.1.5 on 2020-02-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20200218_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='monument_reviews',
        ),
    ]
